# Generated by Django 2.2.3 on 2019-10-02 20:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django_zombodb.indexes
import django_zombodb.operations
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('street', models.TextField()),
                ('zip_code', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        django_zombodb.operations.ZomboDBExtension(
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=django_zombodb.indexes.ZomboDBIndex(field_mapping={'name': {'analyzer': 'fulltext_with_shingles', 'copy_to': 'zdb_all', 'search_analyzer': 'fulltext_with_shingles_search', 'type': 'text'}, 'street': {'analyzer': 'fulltext_with_shingles', 'copy_to': 'zdb_all', 'search_analyzer': 'fulltext_with_shingles_search', 'type': 'text'}}, fields=['name', 'street', 'zip_code', 'city', 'state', 'phone', 'categories'], name='restaurants_name_72ba02_zombodb'),
        ),
    ]
