# Generated by Django 2.1.7 on 2019-03-01 13:05

from django.db import migrations
import django_zombodb.indexes
import django_zombodb.operations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        django_zombodb.operations.ZomboDBExtension(),
        migrations.AddIndex(
            model_name='restaurant',
            index=django_zombodb.indexes.ZomboDBIndex(fields=['name', 'street', 'zip_code', 'city', 'state', 'phone', 'categories'], name='restaurants_name_72ba02_zombodb'),
        ),
    ]
