# Generated by Django 2.1.5 on 2019-02-01 23:11

from django.db import migrations
import django_zombodb.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='restaurant',
            index=django_zombodb.indexes.ZomboDBIndex(fields=['name', 'street', 'categories'], name='restaurants_name_4788bf_idx'),
        ),
    ]
