# Generated by Django 2.1.5 on 2019-02-04 20:39

from django.db import migrations
import django_zombodb.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190204_1935'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_name_016c1c_zombodb',
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=django_zombodb.indexes.ZomboDBIndex(fields=['name', 'street', 'zip_code', 'city', 'state', 'phone', 'categories'], name='restaurants_name_72ba02_zombodb'),
        ),
    ]
