# Generated by Django 2.2.2 on 2019-07-17 22:32

from django.db import migrations
import django_zombodb.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190301_1305'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_name_72ba02_zombodb',
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=django_zombodb.indexes.ZomboDBIndex(field_mapping={'name': {'analyzer': 'fulltext_with_shingles', 'copy_to': 'zdb_all', 'search_analyzer': 'fulltext_with_shingles_search', 'type': 'text'}, 'street': {'analyzer': 'zdb_standard', 'copy_to': 'zdb_all', 'type': 'text'}}, fields=['name', 'street', 'zip_code', 'city', 'state', 'phone', 'categories'], name='restaurants_name_72ba02_zombodb'),
        ),
    ]
