# Generated by Django 2.1.5 on 2019-02-11 22:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django_zombodb.indexes
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_setup_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('street', models.TextField()),
                ('zip_code', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=django_zombodb.indexes.ZomboDBIndex(fields=['name', 'street', 'zip_code', 'city', 'state', 'phone', 'email', 'website', 'categories'], name='restaurants_name_f38813_zombodb', url='http://localhost:9200/'),
        ),
    ]
